// flow-typed signature: 2231c47919cbdee6ea7a9e01782690e7
// flow-typed version: <<STUB>>/db_v^1.0.6/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'db' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'db/db' {
  declare module.exports: any;
}

declare module 'db/docroot/db' {
  declare module.exports: any;
}

declare module 'db/ds' {
  declare module.exports: any;
}

declare module 'db/dynamo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'db/db.js' {
  declare module.exports: $Exports<'db/db'>;
}
declare module 'db/docroot/db.js' {
  declare module.exports: $Exports<'db/docroot/db'>;
}
declare module 'db/ds.js' {
  declare module.exports: $Exports<'db/ds'>;
}
declare module 'db/dynamo.js' {
  declare module.exports: $Exports<'db/dynamo'>;
}
