// flow-typed signature: a223856393566d98231a8dc292acd5ad
// flow-typed version: <<STUB>>/multitrim_v^2.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multitrim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multitrim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'multitrim/index' {
  declare module.exports: $Exports<'multitrim'>;
}
declare module 'multitrim/index.js' {
  declare module.exports: $Exports<'multitrim'>;
}
