// flow-typed signature: c6cfeab373384a453138b2bdacd0608a
// flow-typed version: <<STUB>>/object_v^0.1.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object/lib/object' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object/index' {
  declare module.exports: $Exports<'object'>;
}
declare module 'object/index.js' {
  declare module.exports: $Exports<'object'>;
}
declare module 'object/lib/object.js' {
  declare module.exports: $Exports<'object/lib/object'>;
}
