// flow-typed signature: e15b8fb02c3feeacf3935607a956aba9
// flow-typed version: <<STUB>>/object-loops_v^0.8.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-loops'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-loops' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-loops/chain' {
  declare module.exports: any;
}

declare module 'object-loops/every' {
  declare module.exports: any;
}

declare module 'object-loops/filter' {
  declare module.exports: any;
}

declare module 'object-loops/find-key' {
  declare module.exports: any;
}

declare module 'object-loops/find' {
  declare module.exports: any;
}

declare module 'object-loops/for-each' {
  declare module.exports: any;
}

declare module 'object-loops/inverse' {
  declare module.exports: any;
}

declare module 'object-loops/keys-in' {
  declare module.exports: any;
}

declare module 'object-loops/keys' {
  declare module.exports: any;
}

declare module 'object-loops/map-keys' {
  declare module.exports: any;
}

declare module 'object-loops/map' {
  declare module.exports: any;
}

declare module 'object-loops/reduce' {
  declare module.exports: any;
}

declare module 'object-loops/some' {
  declare module.exports: any;
}

declare module 'object-loops/test/fixtures/all-method-names' {
  declare module.exports: any;
}

declare module 'object-loops/test/fixtures/reset-object-prototype' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-chain' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-every' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-filter' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-find-key' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-find' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-for-each' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-index' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-inverse' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-keys-in' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-keys' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-map-keys' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-map' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-reduce' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-some' {
  declare module.exports: any;
}

declare module 'object-loops/test/test-values' {
  declare module.exports: any;
}

declare module 'object-loops/test/values-in' {
  declare module.exports: any;
}

declare module 'object-loops/values-in' {
  declare module.exports: any;
}

declare module 'object-loops/values' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-loops/chain.js' {
  declare module.exports: $Exports<'object-loops/chain'>;
}
declare module 'object-loops/every.js' {
  declare module.exports: $Exports<'object-loops/every'>;
}
declare module 'object-loops/filter.js' {
  declare module.exports: $Exports<'object-loops/filter'>;
}
declare module 'object-loops/find-key.js' {
  declare module.exports: $Exports<'object-loops/find-key'>;
}
declare module 'object-loops/find.js' {
  declare module.exports: $Exports<'object-loops/find'>;
}
declare module 'object-loops/for-each.js' {
  declare module.exports: $Exports<'object-loops/for-each'>;
}
declare module 'object-loops/index' {
  declare module.exports: $Exports<'object-loops'>;
}
declare module 'object-loops/index.js' {
  declare module.exports: $Exports<'object-loops'>;
}
declare module 'object-loops/inverse.js' {
  declare module.exports: $Exports<'object-loops/inverse'>;
}
declare module 'object-loops/keys-in.js' {
  declare module.exports: $Exports<'object-loops/keys-in'>;
}
declare module 'object-loops/keys.js' {
  declare module.exports: $Exports<'object-loops/keys'>;
}
declare module 'object-loops/map-keys.js' {
  declare module.exports: $Exports<'object-loops/map-keys'>;
}
declare module 'object-loops/map.js' {
  declare module.exports: $Exports<'object-loops/map'>;
}
declare module 'object-loops/reduce.js' {
  declare module.exports: $Exports<'object-loops/reduce'>;
}
declare module 'object-loops/some.js' {
  declare module.exports: $Exports<'object-loops/some'>;
}
declare module 'object-loops/test/fixtures/all-method-names.js' {
  declare module.exports: $Exports<'object-loops/test/fixtures/all-method-names'>;
}
declare module 'object-loops/test/fixtures/reset-object-prototype.js' {
  declare module.exports: $Exports<'object-loops/test/fixtures/reset-object-prototype'>;
}
declare module 'object-loops/test/test-chain.js' {
  declare module.exports: $Exports<'object-loops/test/test-chain'>;
}
declare module 'object-loops/test/test-every.js' {
  declare module.exports: $Exports<'object-loops/test/test-every'>;
}
declare module 'object-loops/test/test-filter.js' {
  declare module.exports: $Exports<'object-loops/test/test-filter'>;
}
declare module 'object-loops/test/test-find-key.js' {
  declare module.exports: $Exports<'object-loops/test/test-find-key'>;
}
declare module 'object-loops/test/test-find.js' {
  declare module.exports: $Exports<'object-loops/test/test-find'>;
}
declare module 'object-loops/test/test-for-each.js' {
  declare module.exports: $Exports<'object-loops/test/test-for-each'>;
}
declare module 'object-loops/test/test-index.js' {
  declare module.exports: $Exports<'object-loops/test/test-index'>;
}
declare module 'object-loops/test/test-inverse.js' {
  declare module.exports: $Exports<'object-loops/test/test-inverse'>;
}
declare module 'object-loops/test/test-keys-in.js' {
  declare module.exports: $Exports<'object-loops/test/test-keys-in'>;
}
declare module 'object-loops/test/test-keys.js' {
  declare module.exports: $Exports<'object-loops/test/test-keys'>;
}
declare module 'object-loops/test/test-map-keys.js' {
  declare module.exports: $Exports<'object-loops/test/test-map-keys'>;
}
declare module 'object-loops/test/test-map.js' {
  declare module.exports: $Exports<'object-loops/test/test-map'>;
}
declare module 'object-loops/test/test-reduce.js' {
  declare module.exports: $Exports<'object-loops/test/test-reduce'>;
}
declare module 'object-loops/test/test-some.js' {
  declare module.exports: $Exports<'object-loops/test/test-some'>;
}
declare module 'object-loops/test/test-values.js' {
  declare module.exports: $Exports<'object-loops/test/test-values'>;
}
declare module 'object-loops/test/values-in.js' {
  declare module.exports: $Exports<'object-loops/test/values-in'>;
}
declare module 'object-loops/values-in.js' {
  declare module.exports: $Exports<'object-loops/values-in'>;
}
declare module 'object-loops/values.js' {
  declare module.exports: $Exports<'object-loops/values'>;
}
