// flow-typed signature: 04f99ad405a9bacc73ef3f0114dfa04b
// flow-typed version: <<STUB>>/r2_v^2.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'r2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'r2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'r2/test/test-basics' {
  declare module.exports: any;
}

declare module 'r2/test/test-errors' {
  declare module.exports: any;
}

declare module 'r2/test/test-responses' {
  declare module.exports: any;
}

// Filename aliases
declare module 'r2/index' {
  declare module.exports: $Exports<'r2'>;
}
declare module 'r2/index.js' {
  declare module.exports: $Exports<'r2'>;
}
declare module 'r2/test/test-basics.js' {
  declare module.exports: $Exports<'r2/test/test-basics'>;
}
declare module 'r2/test/test-errors.js' {
  declare module.exports: $Exports<'r2/test/test-errors'>;
}
declare module 'r2/test/test-responses.js' {
  declare module.exports: $Exports<'r2/test/test-responses'>;
}
