// flow-typed signature: e6c52f9a556eb40f51ea8d07b9de98e1
// flow-typed version: <<STUB>>/shimmer_v^1.2.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shimmer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shimmer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shimmer/test/init.tap' {
  declare module.exports: any;
}

declare module 'shimmer/test/massUnwrap.tap' {
  declare module.exports: any;
}

declare module 'shimmer/test/massWrap.tap' {
  declare module.exports: any;
}

declare module 'shimmer/test/unwrap.tap' {
  declare module.exports: any;
}

declare module 'shimmer/test/wrap.tap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shimmer/index' {
  declare module.exports: $Exports<'shimmer'>;
}
declare module 'shimmer/index.js' {
  declare module.exports: $Exports<'shimmer'>;
}
declare module 'shimmer/test/init.tap.js' {
  declare module.exports: $Exports<'shimmer/test/init.tap'>;
}
declare module 'shimmer/test/massUnwrap.tap.js' {
  declare module.exports: $Exports<'shimmer/test/massUnwrap.tap'>;
}
declare module 'shimmer/test/massWrap.tap.js' {
  declare module.exports: $Exports<'shimmer/test/massWrap.tap'>;
}
declare module 'shimmer/test/unwrap.tap.js' {
  declare module.exports: $Exports<'shimmer/test/unwrap.tap'>;
}
declare module 'shimmer/test/wrap.tap.js' {
  declare module.exports: $Exports<'shimmer/test/wrap.tap'>;
}
