// flow-typed signature: bc84f40d9880b004f7dbe7d4c83366c9
// flow-typed version: <<STUB>>/wtfnode_v^0.5.7/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wtfnode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wtfnode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wtfnode/clustertest' {
  declare module.exports: any;
}

declare module 'wtfnode/kitchensink' {
  declare module.exports: any;
}

declare module 'wtfnode/proxy' {
  declare module.exports: any;
}

declare module 'wtfnode/test-promisify' {
  declare module.exports: any;
}

declare module 'wtfnode/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wtfnode/clustertest.js' {
  declare module.exports: $Exports<'wtfnode/clustertest'>;
}
declare module 'wtfnode/index' {
  declare module.exports: $Exports<'wtfnode'>;
}
declare module 'wtfnode/index.js' {
  declare module.exports: $Exports<'wtfnode'>;
}
declare module 'wtfnode/kitchensink.js' {
  declare module.exports: $Exports<'wtfnode/kitchensink'>;
}
declare module 'wtfnode/proxy.js' {
  declare module.exports: $Exports<'wtfnode/proxy'>;
}
declare module 'wtfnode/test-promisify.js' {
  declare module.exports: $Exports<'wtfnode/test-promisify'>;
}
declare module 'wtfnode/test.js' {
  declare module.exports: $Exports<'wtfnode/test'>;
}
